class GithubApiFields:
    ACCOUNT = "account"
    TYPE = "type"
    LOGIN = "login"
    OWNER = "owner"
    REPOSITORY = "repository"
    REPOSITORIES = "repositories"
    INSTALLATION = "installation"
    INSTALLATIONS = "installations"
    ACTION = "action"
    NUMBER = "number"
    NAME = "name"
    ID = "id"
    REF = "ref"
