class GithubApiFields:
    ACCOUNT_FIELD = "account"
    TYPE_FIELD = "type"
    LOGIN_FIELD = "login"
    OWNER_FIELD = "owner"
    REPOSITORY_FIELD = "repository"
    REPOSITORIES_FIELD = "repositories"
    INSTALLATION_FIELD = "installation"
    INSTALLATIONS_FIELD = "installations"
    ACTION_FIELD = "action"
    NUMBER_FIELD = "number"
    NAME_FIELD = "name"
    ID_FIELD = "id"
    REF_FIELD = "ref"
