class ModelFields:
    """
    All the fields used for the various models in the server and the database, this class is used to ensure coherence
    in naming accross all of the backend.
    """

    GITHUB_ACCOUNT_LOGIN = "github_account_login"
    REPO_NAME = "repo_name"
    DIR_PATH = "dir_path"
    TYPE = "type"
    CONTENT = "content"
    MONGO_ID = "_id"
    COUNTER = "counter"
    NAME = "name"
    REFS = "refs"
    ID = "id"
    SHA_LAST_UPDATE = "sha_last_update"
    LOGIN = "login"
    PATH = "path"
    START_LINE = "start_line"
    END_LINE = "end_line"
    IS_DELETED = "is_deleted"
    EXPIRES_AT = "expires_at"
    FULL_NAME = "full_name"
    OWNER_TYPE = "owner_type"
    PRIVATE = "private"
    SUB_FS_NODES = "sub_fs_nodes"
    TOKEN = "token"
    CODE = "code"
    DOC_NAME = "doc_name"
    USER_LOGIN = "user_login"
    FS_NODE_NAME = "fs_node_name"
