apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongod.conf: |
    net:
      port: 27017
      bindIp: 0.0.0.0

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
spec:
 serviceName: mongo
 replicas: 1
 selector:
   matchLabels:
     app: mongo
 template:
   metadata:
     labels:
       app: mongo
   spec:
     terminationGracePeriodSeconds: 0
     containers:
       - name: mongo
         image: mongo
         command: ["/bin/sh", "-c", "mongod --config /usr/local/etc/mongod.conf"]
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: mongo-claim
             mountPath: /data/db
           - name: mongo-config
             mountPath: /usr/local/etc
     volumes:
       - name: mongo-claim
         persistentVolumeClaim:
           claimName: mongo-claim
       - name: mongo-config
         configMap:
           name: mongo-config

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-claim
spec:
  storageClassName: mongo-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  labels:
    type: local
spec:
  storageClassName: mongo-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/codersdoc/mongo" # we will write to this folder on our local machine
